version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.2-stretch-browsers
    steps:
      paths:
        - ~/ethlend

    steps:
      - run:
          name: Install dependencies
          command: npm install


